import type { PortfolioData } from '../hooks/useUserData'

/**
 * Turn a portfolio into a LaTeX resume.
 *
 * Deterministic rather than another AI call: the content has already been
 * refined by Suggest a Fix, and this step is pure formatting. That also means
 * it costs nothing and cannot hallucinate a job you never had.
 */

/**
 * Escape LaTeX's special characters.
 *
 * Skipping this is the classic way to produce a .tex that will not compile:
 * a single "R&D" or "100%" in someone's resume breaks the build, and the
 * error Overleaf reports points at the wrong line.
 */
function tex(input: string | undefined | null): string {
  if (!input) return ''
  return input
    .replace(/\\/g, '\\textbackslash{}')
    .replace(/([&%$#_{}])/g, '\\$1')
    .replace(/~/g, '\\textasciitilde{}')
    .replace(/\^/g, '\\textasciicircum{}')
    // Straight quotes read as the wrong glyph in LaTeX output.
    .replace(/"/g, "''")
}

/**
 * A URL for \href. Escaping differs from body text: the characters still need
 * neutralising, but hyperref decodes them back, so the link stays correct.
 * An unescaped & from a query string (`?a=1&b=2`) is enough to fail the build.
 */
function texUrl(input: string | undefined | null): string {
  if (!input) return ''
  const trimmed = input.trim()
  const withScheme = /^https?:\/\//i.test(trimmed) ? trimmed : `https://${trimmed}`
  return withScheme.replace(/([%#&_\\{}])/g, '\\$1')
}

function section(title: string, body: string): string {
  return body.trim() ? `\\section*{${tex(title)}}\n${body}\n` : ''
}

export function buildResumeLatex(p: PortfolioData): string {
  const contacts = [
    p.email && `\\href{mailto:${p.email.trim()}}{${tex(p.email)}}`,
    p.github && `\\href{${texUrl(p.github)}}{${tex(p.github)}}`,
    p.linkedin && `\\href{${texUrl(p.linkedin)}}{${tex(p.linkedin)}}`,
    ...(p.customLinks ?? []).map((l) =>
      l.url ? `\\href{${texUrl(l.url)}}{${tex(l.label || l.url)}}` : ''
    ),
  ].filter(Boolean).join(' \\quad ')

  const experience = (p.experience ?? []).map((e) => `\\entry{${tex(e.role)}}{${tex(e.company)}}{${tex(e.period)}}
${tex(e.description)}
`).join('\n')

  const education = (p.education ?? []).map((e) => `\\entry{${tex(e.degree)}}{${tex(e.institution)}}{${tex(e.period)}}
${tex(e.description)}
`).join('\n')

  const projects = (p.projects ?? []).map((pr) => {
    const heading = pr.link?.trim()
      ? `\\href{${texUrl(pr.link)}}{${tex(pr.name)}}`
      : tex(pr.name)
    return `\\item \\textbf{${heading}} --- ${tex(pr.description)}`
  }).join('\n')

  const skills = (p.skills ?? []).map(tex).join(' $\\cdot$ ')

  const custom = (p.customSections ?? []).map((cs) => section(
    cs.title,
    `\\begin{itemize}[leftmargin=*, itemsep=2pt, topsep=2pt]\n` +
    (cs.items ?? []).map((it) => `\\item \\textbf{${tex(it.name)}} --- ${tex(it.description)}`).join('\n') +
    `\n\\end{itemize}`
  )).join('\n')

  return `% Generated by Portflow — https://portflow.co.in
% Upload this file to Overleaf (New Project -> Upload Project) and compile.
\\documentclass[11pt,a4paper]{article}

\\usepackage[left=0.7in, right=0.7in, top=1cm, bottom=1cm]{geometry}
\\usepackage[hidelinks]{hyperref}
\\usepackage{enumitem}
\\usepackage{titlesec}
\\usepackage[T1]{fontenc}

\\titleformat{\\section}{\\large\\bfseries}{}{0pt}{}[\\titlerule]
\\titlespacing{\\section}{0pt}{10pt}{6pt}
\\setlength{\\parindent}{0pt}
\\pagestyle{empty}
\\setlength{\\headsep}{0pt}
\\setlength{\\topskip}{0pt}

% role / organisation / dates on one line
\\newcommand{\\entry}[3]{%
  \\vspace{4pt}\\textbf{#1}\\hfill\\textit{#3}\\\\%
  \\textit{#2}\\\\[2pt]%
}

\\begin{document}

\\begin{center}
  {\\LARGE\\bfseries ${tex(p.name) || 'Your Name'}}\\\\[4pt]
  ${tex(p.title)}\\\\[4pt]
  \\small ${contacts}
\\end{center}

${section('Summary', tex(p.bio))}
${section('Experience', experience)}
${section('Education', education)}
${projects ? section('Projects', `\\begin{itemize}[leftmargin=*, itemsep=2pt, topsep=2pt]\n${projects}\n\\end{itemize}`) : ''}
${section('Skills', skills)}
${custom}
\\end{document}
`
}

/** Trigger a download of the .tex file. */
export function downloadResumeLatex(portfolio: PortfolioData) {
  const blob = new Blob([buildResumeLatex(portfolio)], { type: 'application/x-tex' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  const slug = (portfolio.name || 'resume').trim().toLowerCase().replace(/[^a-z0-9]+/g, '-') || 'resume'
  link.href = url
  link.download = `${slug}.tex`
  document.body.appendChild(link)
  link.click()
  link.remove()
  URL.revokeObjectURL(url)
}

/**
 * Open the document straight in Overleaf.
 *
 * Overleaf accepts a document posted as a form field, so this needs no
 * hosting and no upload step - the browser submits the source directly.
 */
export function openInOverleaf(portfolio: PortfolioData) {
  const form = document.createElement('form')
  form.method = 'POST'
  form.action = 'https://www.overleaf.com/docs'
  form.target = '_blank'
  form.style.display = 'none'

  const field = document.createElement('input')
  field.type = 'hidden'
  field.name = 'snip'
  field.value = buildResumeLatex(portfolio)
  form.appendChild(field)

  const name = document.createElement('input')
  name.type = 'hidden'
  name.name = 'snip_name'
  name.value = `${(portfolio.name || 'Resume').trim()} — Resume`
  form.appendChild(name)

  document.body.appendChild(form)
  form.submit()
  form.remove()
}
